### ISSUE TITLE
ascii Encoding problem…

### ISSUE THREAD

**Issue by GrugBe** [fniephaus/alfred-dropbox#3]
Recently, I've installed OsX El Capitan, and now, I have this error  when I browse a dropbox (a problem with the accents in folder name) :

Error in workflow 'com.fniephaus.dropbox'
'ascii' codec can't encode character u'\xe9' in position 37 origninal not in range(128)

![screencapture](https://monosnap.com/file/yrHIc26eTPZptYKFEWa47qr48wz1Ld.png)

Do you know how I can fix that ?

- python version?

**Comment by fniephaus** [comment]
This seems to be a bug in the workflow. `\xe9` is supposed to be an `é`.
Could you please provide a debug log using the [Workflow Debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/)? And please make sure not to include any sensitive information. :)

**Comment by GrugBe** [comment]
Starting debug for 'Dropbox for Alfred'

[2016-09-04 18:52:18][STDERR: input.scriptfilter] Workflow version : 2.0.0
The debug log can be found in the log file:
/Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/com.fniephaus.dropbox.log
Workflow version : 2.0.0
The debug log can be found in the log file:
/Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/com.fniephaus.dropbox.log
Workflow finished in 0.027 seconds.
Workflow finished in 0.028 seconds.
Workflow finished in 1.840 seconds.
[2016-09-04 18:52:26][STDERR: input.scriptfilter] Workflow version : 2.0.0
The debug log can be found in the log file:
/Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/com.fniephaus.dropbox.log
Workflow version : 2.0.0
The debug log can be found in the log file:
/Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/com.fniephaus.dropbox.log
Workflow finished in 0.020 seconds.
Workflow finished in 0.021 seconds.
Workflow finished in 1.198 seconds.
[2016-09-04 18:52:29][STDERR: input.scriptfilter] Workflow version : 2.0.0
The debug log can be found in the log file:
/Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/com.fniephaus.dropbox.log
Workflow version : 2.0.0
The debug log can be found in the log file:
/Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/com.fniephaus.dropbox.log
Workflow finished in 0.022 seconds.
Workflow finished in 0.023 seconds.
Workflow finished in 1.052 seconds.
[2016-09-04 18:52:30][ERROR: input.scriptfilter] Code 1: Workflow version : 2.0.0
The debug log can be found in the log file:
/Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/com.fniephaus.dropbox.log
For assistance, see: https://github.com/fniephaus/alfred-dropbox/issues
Workflow finished in 0.064 seconds.

**Comment by fniephaus** [comment]
Sorry, but I can't tell from the log you provided what's causing your issues. What's inside the `com.fniephaus.dropbox.log` file? Have you triggered the issue while in debug mode?

**Comment by GrugBe** [comment]
ok, sorry this is the content of the com.fniephaus.dropbox.log : 


00:21:13 workflow.py:2154 DEBUG    Workflow version : 2.0.0
00:21:13 workflow.py:1556 DEBUG    Reading settings from `/Users/Grug/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.dropbox/settings.json` ...
00:21:13 workflow.py:2443 DEBUG    Update check not due
00:21:13 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/__workflow_update_status.cpickle
00:21:13 workflow.py:2371 DEBUG    update_data : {u'available': False}
00:21:13 workflow.py:2563 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
00:21:13 workflow.py:2563 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
00:21:14 workflow.py:1827 DEBUG    Cached data saved at : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_accounts.cpickle
00:21:14 workflow.py:2353 DEBUG    Set last run version : 2.0.0
00:21:14 workflow.py:2197 DEBUG    Workflow finished in 1.656 seconds.
00:21:15 workflow.py:2154 DEBUG    Workflow version : 2.0.0
00:21:15 workflow.py:1556 DEBUG    Reading settings from `/Users/Grug/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.dropbox/settings.json` ...
00:21:15 workflow.py:2443 DEBUG    Update check not due
00:21:15 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/__workflow_update_status.cpickle
00:21:15 workflow.py:2371 DEBUG    update_data : {u'available': False}
00:21:16 workflow.py:2563 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
00:21:16 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_accounts.cpickle
00:21:16 background.py:188 DEBUG    Command arguments cached to `/Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_prefetch_452048412_6666cd76f96956469e7be39d750cc7d9.argcache`
00:21:16 background.py:192 DEBUG    Calling [u'/usr/bin/python', '/Users/Grug/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.04933F64-098B-45B0-8DDA-BBB12C56C1D9/workflow/background.pyc', u'dropbox_prefetch_452048412_6666cd76f96956469e7be39d750cc7d9'] ...
00:21:16 workflow.py:2154 DEBUG    Workflow version : 2.0.0
00:21:16 workflow.py:2197 DEBUG    Workflow finished in 0.031 seconds.
00:21:16 workflow.py:2197 DEBUG    Workflow finished in 0.033 seconds.
00:21:16 background.py:236 DEBUG    Task `dropbox_prefetch_452048412_6666cd76f96956469e7be39d750cc7d9` running
00:21:16 background.py:237 DEBUG    cmd : ['/usr/bin/python', u'/Users/Grug/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.04933F64-098B-45B0-8DDA-BBB12C56C1D9/dropbox_prefetch.py', u'452048412', '/']
00:21:16 background.py:197 DEBUG    Executing task `dropbox_prefetch_452048412_6666cd76f96956469e7be39d750cc7d9` in background...
00:21:16 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/452048412_6666cd76f96956469e7be39d750cc7d9.cpickle
00:21:16 workflow.py:2563 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
00:21:16 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_accounts.cpickle
00:21:16 background.py:248 DEBUG    Task `dropbox_prefetch_452048412_6666cd76f96956469e7be39d750cc7d9` finished
00:21:16 workflow.py:1556 DEBUG    Reading settings from `/Users/Grug/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.dropbox/settings.json` ...
00:21:16 workflow.py:2353 DEBUG    Set last run version : 2.0.0
00:21:16 workflow.py:2197 DEBUG    Workflow finished in 0.186 seconds.
00:21:17 workflow.py:1827 DEBUG    Cached data saved at : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/452048412_6666cd76f96956469e7be39d750cc7d9.cpickle
00:21:17 workflow.py:2353 DEBUG    Set last run version : 2.0.0
00:21:17 workflow.py:2197 DEBUG    Workflow finished in 1.282 seconds.
00:21:22 workflow.py:2154 DEBUG    Workflow version : 2.0.0
00:21:22 workflow.py:1556 DEBUG    Reading settings from `/Users/Grug/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.dropbox/settings.json` ...
00:21:22 workflow.py:2443 DEBUG    Update check not due
00:21:22 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/__workflow_update_status.cpickle
00:21:22 workflow.py:2371 DEBUG    update_data : {u'available': False}
00:21:22 workflow.py:2563 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
00:21:22 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_accounts.cpickle
00:21:22 background.py:188 DEBUG    Command arguments cached to `/Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_prefetch_452048412_e104e7fc33da163d643aaad5c20f39ed.argcache`
00:21:22 background.py:192 DEBUG    Calling [u'/usr/bin/python', '/Users/Grug/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.04933F64-098B-45B0-8DDA-BBB12C56C1D9/workflow/background.pyc', u'dropbox_prefetch_452048412_e104e7fc33da163d643aaad5c20f39ed'] ...
00:21:22 workflow.py:2154 DEBUG    Workflow version : 2.0.0
00:21:22 workflow.py:2197 DEBUG    Workflow finished in 0.021 seconds.
00:21:22 workflow.py:2197 DEBUG    Workflow finished in 0.022 seconds.
00:21:22 background.py:236 DEBUG    Task `dropbox_prefetch_452048412_e104e7fc33da163d643aaad5c20f39ed` running
00:21:22 background.py:237 DEBUG    cmd : ['/usr/bin/python', u'/Users/Grug/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.04933F64-098B-45B0-8DDA-BBB12C56C1D9/dropbox_prefetch.py', u'452048412', u'/Epicerie Sequentielle']
00:21:22 background.py:197 DEBUG    Executing task `dropbox_prefetch_452048412_e104e7fc33da163d643aaad5c20f39ed` in background...
00:21:22 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/452048412_e104e7fc33da163d643aaad5c20f39ed.cpickle
00:21:22 workflow.py:2563 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
00:21:22 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_accounts.cpickle
00:21:22 background.py:248 DEBUG    Task `dropbox_prefetch_452048412_e104e7fc33da163d643aaad5c20f39ed` finished
00:21:22 workflow.py:1556 DEBUG    Reading settings from `/Users/Grug/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.dropbox/settings.json` ...
00:21:22 workflow.py:2353 DEBUG    Set last run version : 2.0.0
00:21:22 workflow.py:2197 DEBUG    Workflow finished in 0.182 seconds.
00:21:23 workflow.py:1827 DEBUG    Cached data saved at : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/452048412_e104e7fc33da163d643aaad5c20f39ed.cpickle
00:21:23 workflow.py:2353 DEBUG    Set last run version : 2.0.0
00:21:23 workflow.py:2197 DEBUG    Workflow finished in 1.017 seconds.
00:21:25 workflow.py:2154 DEBUG    Workflow version : 2.0.0
00:21:25 workflow.py:1556 DEBUG    Reading settings from `/Users/Grug/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.dropbox/settings.json` ...
00:21:25 workflow.py:2443 DEBUG    Update check not due
00:21:25 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/__workflow_update_status.cpickle
00:21:25 workflow.py:2371 DEBUG    update_data : {u'available': False}
00:21:25 workflow.py:2563 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
00:21:25 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_accounts.cpickle
00:21:25 workflow.py:2176 ERROR    'ascii' codec can't encode character u'\xe9' in position 37: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/Grug/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.04933F64-098B-45B0-8DDA-BBB12C56C1D9/workflow/workflow.py", line 2169, in run
    func(self)
  File "dropbox_filter.py", line 50, in main
    file_or_folder = get_file_or_folder(command, query)
  File "dropbox_filter.py", line 129, in get_file_or_folder
    prefetch(wf, uid, path)
  File "dropbox_filter.py", line 118, in prefetch
    job_name = 'dropbox_prefetch_%s' % get_hash(uid, path)
  File "/Users/Grug/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.04933F64-098B-45B0-8DDA-BBB12C56C1D9/helpers.py", line 32, in get_hash
    return "_".join([uid, hashlib.md5(path).hexdigest()])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 37: ordinal not in range(128)
00:21:25 workflow.py:2179 INFO     For assistance, see: https://github.com/fniephaus/alfred-dropbox/issues
00:21:25 workflow.py:2197 DEBUG    Workflow finished in 0.055 seconds.

**Comment by GrugBe** [comment]
here is what is inside the com.fniephaus.dropbox.log : 


00:21:13 workflow.py:2154 DEBUG    Workflow version : 2.0.0
00:21:13 workflow.py:1556 DEBUG    Reading settings from `/Users/Grug/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.dropbox/settings.json` ...
00:21:13 workflow.py:2443 DEBUG    Update check not due
00:21:13 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/__workflow_update_status.cpickle
00:21:13 workflow.py:2371 DEBUG    update_data : {u'available': False}
00:21:13 workflow.py:2563 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
00:21:13 workflow.py:2563 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
00:21:14 workflow.py:1827 DEBUG    Cached data saved at : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_accounts.cpickle
00:21:14 workflow.py:2353 DEBUG    Set last run version : 2.0.0
00:21:14 workflow.py:2197 DEBUG    Workflow finished in 1.656 seconds.
00:21:15 workflow.py:2154 DEBUG    Workflow version : 2.0.0
00:21:15 workflow.py:1556 DEBUG    Reading settings from `/Users/Grug/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.dropbox/settings.json` ...
00:21:15 workflow.py:2443 DEBUG    Update check not due
00:21:15 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/__workflow_update_status.cpickle
00:21:15 workflow.py:2371 DEBUG    update_data : {u'available': False}
00:21:16 workflow.py:2563 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
00:21:16 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_accounts.cpickle
00:21:16 background.py:188 DEBUG    Command arguments cached to `/Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_prefetch_  <!-- sensitive information. -->_….argcache`
00:21:16 background.py:192 DEBUG    Calling [u'/usr/bin/python', '/Users/Grug/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.049…-C1D9/workflow/background.pyc', u'dropbox_prefetch__…'] ...
00:21:16 workflow.py:2154 DEBUG    Workflow version : 2.0.0
00:21:16 workflow.py:2197 DEBUG    Workflow finished in 0.031 seconds.
00:21:16 workflow.py:2197 DEBUG    Workflow finished in 0.033 seconds.
00:21:16 background.py:236 DEBUG    Task `dropbox_prefetch_<!-- sensitive information ? -->_…` running
00:21:16 background.py:237 DEBUG    cmd : ['/usr/bin/python', u'/Users/Grug/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow./dropbox_prefetch.py', u'', '/']
00:21:16 background.py:197 DEBUG    Executing task `dropbox_prefetch_<!-- sensitive information. -->_…` in background...
00:21:16 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/_….cpickle
00:21:16 workflow.py:2563 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
00:21:16 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_accounts.cpickle
00:21:16 background.py:248 DEBUG    Task `dropbox_prefetch_<!-- sensitive information. -->_…` finished
00:21:16 workflow.py:1556 DEBUG    Reading settings from `/Users/Grug/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.dropbox/settings.json` ...
00:21:16 workflow.py:2353 DEBUG    Set last run version : 2.0.0
00:21:16 workflow.py:2197 DEBUG    Workflow finished in 0.186 seconds.
00:21:17 workflow.py:1827 DEBUG    Cached data saved at : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/_….cpickle
00:21:17 workflow.py:2353 DEBUG    Set last run version : 2.0.0
00:21:17 workflow.py:2197 DEBUG    Workflow finished in 1.282 seconds.
00:21:22 workflow.py:2154 DEBUG    Workflow version : 2.0.0
00:21:22 workflow.py:1556 DEBUG    Reading settings from `/Users/Grug/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.dropbox/settings.json` ...
00:21:22 workflow.py:2443 DEBUG    Update check not due
00:21:22 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/__workflow_update_status.cpickle
00:21:22 workflow.py:2371 DEBUG    update_data : {u'available': False}
00:21:22 workflow.py:2563 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
00:21:22 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_accounts.cpickle
00:21:22 background.py:188 DEBUG    Command arguments cached to `/Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_prefetch_<!-- sensitive information. -->_<!-- may be sensitive information too-->ed.argcache`
00:21:22 background.py:192 DEBUG    Calling [u'/usr/bin/python', '/Users/Grug/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.049…-C1D9/workflow/background.pyc', u'dropbox_prefetch__ed'] ...
00:21:22 workflow.py:2154 DEBUG    Workflow version : 2.0.0
00:21:22 workflow.py:2197 DEBUG    Workflow finished in 0.021 seconds.
00:21:22 workflow.py:2197 DEBUG    Workflow finished in 0.022 seconds.
00:21:22 background.py:236 DEBUG    Task `dropbox_prefetch_<!-- sensitive information. -->_<!-- may be sensitive information too-->ed` running
00:21:22 background.py:237 DEBUG    cmd : ['/usr/bin/python', u'/Users/Grug/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.049…-C1D9/dropbox_prefetch.py', u'', u'/Epicerie Sequentielle']
00:21:22 background.py:197 DEBUG    Executing task `dropbox_prefetch_<!-- sensitive information. -->_<!-- may be sensitive information too-->ed` in background...
00:21:22 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/_ed.cpickle
00:21:22 workflow.py:2563 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
00:21:22 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_accounts.cpickle
00:21:22 background.py:248 DEBUG    Task `dropbox_prefetch_<!-- sensitive information. -->_<!-- may be sensitive information too-->ed` finished
00:21:22 workflow.py:1556 DEBUG    Reading settings from `/Users/Grug/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.dropbox/settings.json` ...
00:21:22 workflow.py:2353 DEBUG    Set last run version : 2.0.0
00:21:22 workflow.py:2197 DEBUG    Workflow finished in 0.182 seconds.
00:21:23 workflow.py:1827 DEBUG    Cached data saved at : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/_ed.cpickle
00:21:23 workflow.py:2353 DEBUG    Set last run version : 2.0.0
00:21:23 workflow.py:2197 DEBUG    Workflow finished in 1.017 seconds.
00:21:25 workflow.py:2154 DEBUG    Workflow version : 2.0.0
00:21:25 workflow.py:1556 DEBUG    Reading settings from `/Users/Grug/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.dropbox/settings.json` ...
00:21:25 workflow.py:2443 DEBUG    Update check not due
00:21:25 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/__workflow_update_status.cpickle
00:21:25 workflow.py:2371 DEBUG    update_data : {u'available': False}
00:21:25 workflow.py:2563 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
00:21:25 workflow.py:1791 DEBUG    Loading cached data from : /Users/Grug/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/dropbox_accounts.cpickle
00:21:25 workflow.py:2176 ERROR    'ascii' codec can't encode character u'\xe9' in position 37: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/Grug/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.049…-C1D9/workflow/workflow.py", line 2169, in run
    func(self)
  File "dropbox_filter.py", line 50, in main
    file_or_folder = get_file_or_folder(command, query)
  File "dropbox_filter.py", line 129, in get_file_or_folder
    prefetch(wf, uid, path)
  File "dropbox_filter.py", line 118, in prefetch
    job_name = 'dropbox_prefetch_%s' % get_hash(uid, path)
  File "/Users/Grug/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.049…-C1D9/helpers.py", line 32, in get_hash
    return "_".join([uid, hashlib.md5(path).hexdigest()])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 37: ordinal not in range(128)
00:21:25 workflow.py:2179 INFO     For assistance, see: https://github.com/fniephaus/alfred-dropbox/issues
00:21:25 workflow.py:2197 DEBUG    Workflow finished in 0.055 seconds.

**Comment by fniephaus** [comment]
Thanks! This is what I've been looking for. I'll let you know as soon as I have a fix for this :)

**Comment by fniephaus** [comment]
Your problem should be fixed in [v2.1](https://github.com/fniephaus/alfred-dropbox/releases/tag/v2.1). 😃

**Comment by GrugBe** [comment]
Yes, it's working.  Thanks a lot ! 👍
